### ISSUE TITLE
Requires undo twice to undo

### ISSUE THREAD

**Issue by atombender** [rubymaniac/vscode-paste-and-indent#1]
Love the extension, but it's annoying that you have to hit undo twice after pasting in order to undo a paste: First, apparently, to undo the formatting, then to undo the paste itself.

**Comment by rubymaniac** [comment]
Yes I know.. It is annoying but with the API that VSCode exposes right now there is not a lot that can be done. If I got control on either the clipboard (which I know is not safe) or the change history of the editor I could make this go away. Right now I can only: 
1. execute the paste command
2. select what's pasted
3. make changes
4. replace selection with the changed text

If you know a better way please share!

**Comment by atombender** [comment]
I see. I guess we'll have to wait for built-in support. Thanks.
