### ISSUE TITLE
Undo after paste-and-indent undoes indentation but not paste

### ISSUE THREAD

**Issue by jifunks** [rubymaniac/vscode-paste-and-indent#5]
Step to reproduce:

1. Copy at least 2 lines without any indentation.
2. Paste&Indent them on a indented with n spaces.
3. Undo (ctrl+z)

Example
Step 1) paste block of text 
```
    {
        "key": "cmd+v",
        "command": "editor.action.clipboardPasteAction",
        "when": "!editorTextFocus"
    },
    // paste here
   
```
(to result in)
```
    {
        "key": "cmd+v",
        "command": "editor.action.clipboardPasteAction",
        "when": "!editorTextFocus"
    },
    // paste here
    {
        "key": "cmd+v",
        "command": "editor.action.clipboardPasteAction",
        "when": "!editorTextFocus"
    },
```

Confirmed paste&indent works. Now pressing undo (ctrl+z) results in:

```
    {
        "key": "cmd+v",
        "command": "editor.action.clipboardPasteAction",
        "when": "!editorTextFocus"
    },
    // paste here
        {
        "key": "cmd+v",
        "command": "editor.action.clipboardPasteAction",
        "when": "!editorTextFocus"
    },
```

Expected result should be: 
```
    {
        "key": "cmd+v",
        "command": "editor.action.clipboardPasteAction",
        "when": "!editorTextFocus"
    },
    // paste here
```

Pressing undo again after this undoes the paste. Unsure of whether or not this is within the scope of your extension but it would be a great feature - I also miss this from sublime so if you figured this out you'd be a hero!

**Comment by rubymaniac** [comment]
Unfortunately VSCode API doesn't allow to alter the text pasted **before** the paste is performed, so it is necessary to paste first and change the pasted text on a second step resulting in this weird behaviour. We have to wait for VSCode to give clipboard access to plugin developers so I am closing this as it is a VSCode issue.

**Comment by katerlouis** [comment]
Does VSCode maybe allow to alter the "undo" history? This way you could "just delete" the entry of pasting "normally" 

– Is your extension even still necessary or am I just missing something?
Just switched to vscode and it baffles me how the devs still haven't provided a proper "paste and indent" natively...
