### ISSUE TITLE
indent error in python

### ISSUE THREAD

**Issue by ewwink** [rubymaniac/vscode-paste-and-indent#7]
the code
```
for name in names:
    print name
```
after cut paste become
```
for name in names:
print name
```

![python-loop](https://cloud.githubusercontent.com/assets/760764/26477720/d9cb593a-41f1-11e7-9b04-13266379967f.gif)

**Comment by rubymaniac** [comment]
@ewwink This plugin does not detect the language being pasted and assumes that the first line and the last line are on the same indentation level, which is *almost* always the case, **except** for offset sensitive languages such as Python, YAML etc. There is an option though called `selectAfter` which somewhat helps with offset sensitive languages, so try that and see if it helps. In the meantime I will see if I can do something better for this case.

**Comment by ewwink** [comment]
tried `"pasteAndIndent.selectAfter": true` but still no effect.

thanks

**Comment by rubymaniac** [comment]
@ewwink the effect of `selectAfter` option is to select the wrongly indented code in order for you to be able to indent it with a single keystroke. Please read more in the README
