### ISSUE TITLE
Stopped working a few weeks ago

### ISSUE THREAD

**Issue by nachocab** [rubymaniac/vscode-paste-and-indent#8]
#I love your extension, but it stopped working recently and I can't figure out why. Just to make sure I have the right test case. In a plain text file, if I copy the "a" and the "b" and then I put my cursor here…

<img width="105" alt="screen shot 2018-02-10 at 12 54 03" src="https://user-images.githubusercontent.com/27538/36064966-7e192ea4-0e61-11e8-8e6c-7cab0b6ea942.png">

… after I paste, it looks like this:

<img width="177" alt="screen shot 2018-02-10 at 12 47 39" src="https://user-images.githubusercontent.com/27538/36064942-27a66de8-0e61-11e8-9090-985019c10502.png">

I was hoping it would look like this:

<img width="126" alt="screen shot 2018-02-10 at 12 53 18" src="https://user-images.githubusercontent.com/27538/36064956-6343947a-0e61-11e8-8e8c-0dd3656d77a8.png">

I can see that I have the right config, that no other actions are assigned to that shortcut with those filters and I've uninstalled it and re-installed the extension and reloaded VSCode
<img width="1057" alt="screen shot 2018-02-10 at 12 56 08" src="https://user-images.githubusercontent.com/27538/36064981-d1639f68-0e61-11e8-89ca-c90cf6b766ce.png">

Is there anything else I can try?

**Comment by rubymaniac** [comment]
In what OS is that happening? I am using it with no problems on a Mac with the latest version of VSCode. Also yeah you have the right test case which I checked and works as you expected.

**Comment by nachocab** [comment]
I'm on a Mac as well. After you told me it was working for you, I figured it out. There is a conflict with the [Overtype](https://github.com/AdamMaras/vscode-overtype) extension. If I disable it, pasteAndIndent works 👍
